jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: pivnet-opsmgr
    params:
      globs: []
- name: upgrade-opsmgr
  plan:
  - aggregate:
    - get: pivnet-opsmgr
      params:
        globs:
        - '*.ova'
      passed:
      - regulator
      trigger: true
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
  - file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: wait-opsman-clear
  - aggregate:
    - file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
      params:
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_SETTINGS_FILENAME: installation.zip
        OPSMAN_USERNAME: {{opsman_admin_username}}
      task: export-opsmgr-settings
    - file: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.yml
      params:
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
      task: exported-opsmgr-diagnostic-report
  - file: pcf-pipelines/tasks/deploy-opsman-vm/task.yml
    params:
      DNS: {{dns}}
      GATEWAY: {{gateway}}
      GOVC_CLUSTER: {{vcenter_cluster}}
      GOVC_DATACENTER: {{vcenter_datacenter}}
      GOVC_DATASTORE: {{vcenter_datastore}}
      GOVC_PASSWORD: {{vcenter_password}}
      GOVC_RESOURCE_POOL: {{vcenter_resource_pool}}
      GOVC_URL: {{vcenter_url}}
      GOVC_USERNAME: {{vcenter_username}}
      NETMASK: {{netmask}}
      NTP: {{ntp}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_IP: {{opsman_ip}}
      OPSMAN_NETWORK: {{opsman_network}}
      OPSMAN_SSH_PASSWORD: {{opsman_ssh_password}}
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
      OPSMAN_VM_FOLDER: {{opsman_vm_folder}}
    task: deploy-opsman-vm
  - file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: import-opsmgr
  - file: pcf-pipelines/tasks/download-pivnet-stemcells/task.yml
    params:
      API_TOKEN: {{pivnet_token}}
      IAAS_TYPE: vsphere
    task: download-stemcells
  - file: pcf-pipelines/tasks/restore-stemcells/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: restore-stemcells
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: apply-changes
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- name: pcf-pipelines
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
  type: git
- name: pivnet-opsmgr
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
  type: pivnet
- name: schedule
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM
  type: time
