groups: []
jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: tile
    params:
      globs: []
- name: upgrade-tile
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-product
      params:
        globs:
        - '*pivotal'
      passed:
      - regulator
      resource: tile
      trigger: true
  - file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: wait-opsman-clear
  - file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: {{iaas_type}}
      NO_PROXY: ""
      OM_IP: ""
      OPS_MGR_PWD: {{opsman_admin_password}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PIVNET_API_TOKEN: {{pivnet_token}}
    task: upload-tile-and-stemcell
  - file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      PRODUCT_NAME: {{product_name}}
    task: stage-tile
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: apply-changes
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- name: pcf-pipelines
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
  type: git
- check_every: {{pivnet_poll_interval}}
  name: tile
  source:
    api_token: {{pivnet_token}}
    product_slug: {{product_slug}}
    product_version: {{product_version_regex}}
    sort_by: semver
  type: pivnet
- name: schedule
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM
  type: time
