groups: []
jobs:
- ensure:
    params:
      file: wipe-output/*.tfstate
    put: terraform-state
  name: wipe-env
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: terraform-state
  - file: pcf-pipelines/install-pcf/gcp/tasks/wipe-env/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
    task: wipe
  serial_groups:
  - terraform
- name: upload-opsman-image
  plan:
  - get: pcf-pipelines
    version:
      ref: v0.15.5-rc.20
  - get: pivnet-opsmgr
    params:
      globs:
      - '*GCP.yml'
    trigger: true
  - file: pcf-pipelines/install-pcf/gcp/tasks/upload-opsman/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
    task: upload
- name: bootstrap-terraform-state
  plan:
  - get: pcf-pipelines
    version:
      ref: v0.15.5-rc.20
  - file: pcf-pipelines/install-pcf/gcp/tasks/create-initial-terraform-state/task.yml
    params:
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      TERRAFORM_STATEFILE_BUCKET: {{terraform_statefile_bucket}}
    task: create-terraform-state
  serial: true
- ensure:
    params:
      file: create-infrastructure-output/*.tfstate
    put: terraform-state
  name: create-infrastructure
  plan:
  - aggregate:
    - get: terraform-state
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-opsmgr
      params:
        globs:
        - '*GCP.yml'
      passed:
      - upload-opsman-image
  - file: pcf-pipelines/install-pcf/gcp/tasks/create-infrastructure/task.yml
    params:
      DB_ACCOUNTDB_PASSWORD: {{db_accountdb_password}}
      DB_ACCOUNTDB_USERNAME: {{db_accountdb_username}}
      DB_APP_USAGE_SERVICE_PASSWORD: {{db_app_usage_service_password}}
      DB_APP_USAGE_SERVICE_USERNAME: {{db_app_usage_service_username}}
      DB_AUTOSCALE_PASSWORD: {{db_autoscale_password}}
      DB_AUTOSCALE_USERNAME: {{db_autoscale_username}}
      DB_CCDB_PASSWORD: {{db_ccdb_password}}
      DB_CCDB_USERNAME: {{db_ccdb_username}}
      DB_DIEGO_PASSWORD: {{db_diego_password}}
      DB_DIEGO_USERNAME: {{db_diego_username}}
      DB_LOCKET_PASSWORD: {{db_locket_password}}
      DB_LOCKET_USERNAME: {{db_locket_username}}
      DB_NETWORKPOLICYSERVERDB_PASSWORD: {{db_networkpolicyserverdb_password}}
      DB_NETWORKPOLICYSERVERDB_USERNAME: {{db_networkpolicyserverdb_username}}
      DB_NFSVOLUMEDB_PASSWORD: {{db_nfsvolumedb_password}}
      DB_NFSVOLUMEDB_USERNAME: {{db_nfsvolumedb_username}}
      DB_NOTIFICATIONS_PASSWORD: {{db_notifications_password}}
      DB_NOTIFICATIONS_USERNAME: {{db_notifications_username}}
      DB_ROUTING_PASSWORD: {{db_routing_password}}
      DB_ROUTING_USERNAME: {{db_routing_username}}
      DB_SILK_PASSWORD: {{db_silk_password}}
      DB_SILK_USERNAME: {{db_silk_username}}
      DB_UAA_PASSWORD: {{db_uaa_password}}
      DB_UAA_USERNAME: {{db_uaa_username}}
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      PCF_ERT_SSL_CERT: {{pcf_ert_ssl_cert}}
      PCF_ERT_SSL_KEY: {{pcf_ert_ssl_key}}
    task: create-infrastructure
  serial_groups:
  - terraform
- name: configure-director
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-opsmgr
      params:
        globs: []
      passed:
      - create-infrastructure
  - file: pcf-pipelines/install-pcf/gcp/tasks/check-opsman-dns/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
    task: check-opsman-dns
  - file: pcf-pipelines/install-pcf/gcp/tasks/config-opsman-auth/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
    task: configure-opsman-auth
  - file: pcf-pipelines/install-pcf/gcp/tasks/config-director/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_REGION: {{gcp_region}}
      GCP_RESOURCE_PREFIX: {{gcp_resource_prefix}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_ZONE_1: {{gcp_zone_1}}
      GCP_ZONE_2: {{gcp_zone_2}}
      GCP_ZONE_3: {{gcp_zone_3}}
      OPS_MGR_PWD: {{pcf_opsman_admin_password}}
      OPS_MGR_TRUSTED_CERTS: {{pcf_opsman_trusted_certs}}
      OPS_MGR_USR: {{pcf_opsman_admin_username}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
    task: configure-director
  serial_groups:
  - opsman
- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-opsmgr
      params:
        globs: []
      passed:
      - configure-director
      trigger: true
  - file: pcf-pipelines/install-pcf/gcp/tasks/deploy-director/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_opsman_admin_password: {{pcf_opsman_admin_password}}
      pcf_opsman_admin_username: {{pcf_opsman_admin_username}}
    task: deploy-director
  serial_groups:
  - opsman
- name: upload-ert
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-opsmgr
      params:
        globs: []
      passed:
      - deploy-director
      trigger: true
    - get: pivnet-product
      params:
        globs:
        - '*pivotal'
      resource: pivnet-elastic-runtime
  - file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: google
      NO_PROXY: ""
      OM_IP: ""
      OPS_MGR_PWD: {{pcf_opsman_admin_password}}
      OPS_MGR_USR: {{pcf_opsman_admin_username}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PIVNET_API_TOKEN: {{pivnet_token}}
    task: upload-tile
  - file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      PRODUCT_NAME: cf
    task: stage-tile
  serial_groups:
  - opsman
- name: deploy-ert
  plan:
  - aggregate:
    - get: pcf-pipelines
      version:
        ref: v0.15.5-rc.20
    - get: pivnet-opsmgr
      params:
        globs: []
      passed:
      - upload-ert
      trigger: true
    - get: terraform-state
  - file: pcf-pipelines/tasks/install-ert/configure-json/task.yml
    params:
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      S3_ENDPOINT: null
      db_accountdb_password: {{db_accountdb_password}}
      db_accountdb_username: {{db_accountdb_username}}
      db_app_usage_service_password: {{db_app_usage_service_password}}
      db_app_usage_service_username: {{db_app_usage_service_username}}
      db_autoscale_password: {{db_autoscale_password}}
      db_autoscale_username: {{db_autoscale_username}}
      db_ccdb_password: {{db_ccdb_password}}
      db_ccdb_username: {{db_ccdb_username}}
      db_diego_password: {{db_diego_password}}
      db_diego_username: {{db_diego_username}}
      db_locket_password: {{db_locket_password}}
      db_locket_username: {{db_locket_username}}
      db_networkpolicyserverdb_password: {{db_networkpolicyserverdb_password}}
      db_networkpolicyserverdb_username: {{db_networkpolicyserverdb_username}}
      db_nfsvolumedb_password: {{db_nfsvolumedb_password}}
      db_nfsvolumedb_username: {{db_nfsvolumedb_username}}
      db_notifications_password: {{db_notifications_password}}
      db_notifications_username: {{db_notifications_username}}
      db_routing_password: {{db_routing_password}}
      db_routing_username: {{db_routing_username}}
      db_silk_password: {{db_silk_password}}
      db_silk_username: {{db_silk_username}}
      db_uaa_password: {{db_uaa_password}}
      db_uaa_username: {{db_uaa_username}}
      gcp_storage_access_key: {{gcp_storage_access_key}}
      gcp_storage_secret_key: {{gcp_storage_secret_key}}
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      pcf_az_1: {{gcp_zone_1}}
      pcf_az_2: {{gcp_zone_2}}
      pcf_az_3: {{gcp_zone_3}}
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_ert_ssl_cert: {{pcf_ert_ssl_cert}}
      pcf_ert_ssl_key: {{pcf_ert_ssl_key}}
      pcf_iaas: gcp
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
      terraform_prefix: {{gcp_resource_prefix}}
      terraform_template: default
    task: configure-json
  - file: pcf-pipelines/tasks/install-ert/configure-ert/task.yml
    params:
      pcf_ert_domain: {{pcf_ert_domain}}
      pcf_iaas: gcp
      pcf_opsman_admin: {{pcf_opsman_admin_username}}
      pcf_opsman_admin_passwd: {{pcf_opsman_admin_password}}
    task: configure-ert
  - file: pcf-pipelines/tasks/disable-errands/task.yml
    params:
      ERRANDS_TO_DISABLE: {{ert_errands_to_disable}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      PRODUCT_NAME: cf
    task: disable-errands
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
    task: deploy-ert
  serial_groups:
  - opsman
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
- name: gcs
  source:
    repository: frodenas/gcs-resource
  type: docker-image
resources:
- name: pcf-pipelines
  source:
    branch: master
    private_key: {{git_private_key}}
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
  type: git
- name: terraform-state
  source:
    bucket: {{terraform_statefile_bucket}}
    json_key: {{gcp_service_account_key}}
    versioned_file: terraform.tfstate
  type: gcs
- check_every: 4h
  name: pivnet-opsmgr
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
  type: pivnet
- check_every: 4h
  name: pivnet-elastic-runtime
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver
  type: pivnet
